FROM node:12.16-alpine

ENV CODE /opt/app
WORKDIR ${CODE}

RUN apk add --no-cache make gcc g++ python

COPY yarn.lock .
COPY package.json .

RUN yarn install && \
    npm rebuild bcrypt --build-from-source && \
    apk del make gcc g++ python

ENTRYPOINT [ "yarn" ]
