name: CI/CD

on:
    push:
        branches:
            - master
        pull_request:
            - master

jobs:
    test:
        runs-on: ubuntu-latest
        name: Run automated tests
        steps:
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            - uses: actions/checkout@v2
            # Runs a set of commands using the runners shell
            - name: run unit tests
              run: |
                yarn install
                yarn test
